### ISSUE TITLE
Problem in "Open file using external software" feature for document node

### ISSUE THREAD

**Issue by VMarsocci** [zalmoxes-laran/ExtendedMatrix#2]
Hi all, thanks for your work.

I can use any feature of your add-on but not the "Open file using external software", when I come to the Paradata manager for opening the Doc's URL. The command doesn't raise any error but it tries to open the doc with a browser, not successing in opening the proper document (e.g. pdf or jpg).

Even when changing the default options of my OS and Blender's preferences, this bug is not fixed.

My Blender version is 3.6 and my EM Tools is 1.4 dev7. The same issue is occurring in other users' machines, as they follow precisely the same pipeline installing Blender and then EM Tools.

On behalf of Alessandro Spadaro too, thank you very much for your attention!

**Comment by zalmoxes-laran** [comment]
Dears I fixed the problem and added other things. Name of the new release ? Dev 8 release "Spadaro"

- Fixed an annoying bug that prevented the opening of resources on disk using default applications (i.e. images or PDF)
- Added support to recognise and open urls that are instead web urls (i.e. www.indianajonesrules.org)
- Added automatic population of paradata nodes from the files stored in the DosCo
- Added an advanced section in the DosCo box
- Added function to export a csv with the metrics of the proxies (volume, surface, etc.)
- support for Blender 4
- minor bug fixes
